# Form implementation generated from reading ui file 'src/ui/chart_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_setting = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_setting.setGeometry(QtCore.QRect(20, 10, 921, 98))
        self.groupBox_setting.setObjectName("groupBox_setting")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_setting)
        self.gridLayout.setObjectName("gridLayout")
        self.label_stock_id = QtWidgets.QLabel(parent=self.groupBox_setting)
        self.label_stock_id.setMinimumSize(QtCore.QSize(90, 0))
        self.label_stock_id.setText("")
        self.label_stock_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_stock_id.setObjectName("label_stock_id")
        self.gridLayout.addWidget(self.label_stock_id, 2, 2, 1, 1)
        self.label_stock_isin = QtWidgets.QLabel(parent=self.groupBox_setting)
        self.label_stock_isin.setMinimumSize(QtCore.QSize(190, 0))
        self.label_stock_isin.setText("")
        self.label_stock_isin.setObjectName("label_stock_isin")
        self.gridLayout.addWidget(self.label_stock_isin, 1, 1, 1, 2)
        self.label_stock_symbol = QtWidgets.QLabel(parent=self.groupBox_setting)
        self.label_stock_symbol.setMinimumSize(QtCore.QSize(90, 0))
        self.label_stock_symbol.setText("")
        self.label_stock_symbol.setObjectName("label_stock_symbol")
        self.gridLayout.addWidget(self.label_stock_symbol, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.groupBox_setting)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 3, 1)
        self.label_stock_name = QtWidgets.QLabel(parent=self.groupBox_setting)
        self.label_stock_name.setMinimumSize(QtCore.QSize(190, 0))
        self.label_stock_name.setText("")
        self.label_stock_name.setObjectName("label_stock_name")
        self.gridLayout.addWidget(self.label_stock_name, 0, 1, 1, 2)
        self.pushButton_setting = QtWidgets.QPushButton(parent=self.groupBox_setting)
        self.pushButton_setting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.gridLayout.addWidget(self.pushButton_setting, 0, 5, 3, 1)
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.groupBox_setting)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(180, 50))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_search.setFont(font)
        self.lineEdit_search.setClearButtonEnabled(True)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout.addWidget(self.lineEdit_search, 0, 0, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Charting"))
        self.groupBox_setting.setTitle(_translate("MainWindow", "Setting"))
        self.pushButton_setting.setText(_translate("MainWindow", "OK"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "Name, symbol or ISIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
